name: Publish Python Package

on:
  # Trigger the workflow on a push to the main branch or when a release is created
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Check out the code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Install dependencies for building the package
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine

    # Build the package
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    # Publish the package to PyPI
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__          # PyPI username for token-based auth
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # PyPI token from GitHub secrets
      run: |
        python -m twine upload dist/*
